// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image: dynamic(() => import("./Image")),
  rich_text: dynamic(() => import("./RichText")),
  video: dynamic(() => import("./Video")),
};
